### PR TITLE
Restore Debian-specific support for /etc/redis/redis-{server,sentinel}.{pre,post}-{up,down}.d

### PR DESCRIPTION
**Pull request by blinkdog**
This reverts commit 6a9e4d0142b45195a0d55945bbc558df4c48707b.

Devuan downstream needs this run-parts functionality for service state change hooks.
Please consider allowing it to remain? :bowing_man:

### CODE REVIEW

**Comment by lamby** [comment]
@blinkdog Please can you elaborate more on your use-case? :) Thanks!

**Comment by blinkdog** [comment]
@lamby Sure, no problem. My use-case is systems that have migrated downstream, from Debian to Devuan.

Some of these could have scripts that hook state changes in the redis service. An example might be (re)populating the cache from a local or remote source on service start. Another example might be triggering a backup of the persistent store on service stop if the current backup is too old.

In Debian (>= Jessie), one can use the hooks provided by systemd (ExecStartPre, ExecStartPost, ExecStopPre, ExecStopPost) and point them at the script(s). In Devuan, for better or for worse, there is no systemd. Devuan systems rely on the init script to call run-parts to kick off the script(s).

Thank you for considering my pull request. :smile:

**Comment by lamby** [comment]
Hi @blinkdog, thanks for your message.

However do you have any *concrete* examples of users that are are using this? I have never heard of anyone actually using it, with any initsystem.

If a user does 1000% require this feature, then they can simply modify the ``/etc/init.d/redis-server`` initsecript:

* They marked as ``conffiles`` for this reason
* This is what users would have to do with *any other daemon* in Debian

ps. It would be nice if the thread on DNG would calm down and stop emitting such FUD.

**Comment by blinkdog** [comment]
>However do you have any concrete examples of users that are are using this? I have never heard of anyone actually using it, with any initsystem.

No, unfortunately I don't have any information about redis usage beyond the Debian popularity contest:

    #<name> is the package name;
    #<inst> is the number of people who installed this package;
    #<vote> is the number of people who use this package regularly;
    #<old> is the number of people who installed, but don't use this package regularly
    #<recent> is the number of people who upgraded this package recently;
    #<no-files> is the number of people whose entry didn't contain enough information (atime and ctime were 0).
    #rank name                            inst  vote   old recent no-files (maintainer)
    2157  redis-server                    4791  3527   952    310        2 (Chris Lamb)                    

>If a user does 1000% require this feature, then they can simply modify the `/etc/init.d/redis-server` init script:
>* They marked as `conffiles` for this reason
>* This is what users would have to do with _any other daemon_ in Debian

Indeed they could, and honestly I'm not so worried about users coming at it de novo. They are likely to know the change they want to make and will figure it out how to make it happen. I'm more worried about the users with existing scripts who upgrade from Devuan Beowulf to Devuan $(Beowulf+1) who might get caught out without an easy migration path.

I'm just asking since the functionality is already there, and works well in both systemd and sysvinit systems, will you leave it in place to allow these users a smooth upgrade?

>ps. It would be nice if the thread on DNG would calm down and stop emitting such FUD.

Yeah, [the thread on DNG](https://lists.dyne.org/lurker/thread/20171024.133430.668aceae.en.html) runs a bit hot. Unfortunately, 6a9e4d0142b45195a0d55945bbc558df4c48707b touches on many people's darkest fears about systemd in Debian. They just knew it was going to kick their puppy sooner or later, and was that a dog yelping just now?

The truth is closer to puppy's leash was moved to a different hook. My request is aimed toward the low energy solution; can we move the leash back, or is that wall part of the remodeling plans? 

If you are committed to keeping 6a9e4d0142b45195a0d55945bbc558df4c48707b, then Devuan will need to supplement or fork the packaging for redis, which something we'd rather not do if we can help it. So, I thought it would be best to ask first.

And, no hard feelings either way. When I go back to the DNG list, I will tell them that you are reasonable and not a puppy kicker, even if we have to install a new leash hook.

**Comment by lamby** [comment]
> > I'm just asking since the functionality is already there, and works well in both systemd and sysvinit systems, will you leave it in place to allow these users a smooth upgrade?

The smoothest thing to do at this point is remove it early on in the buster release cycle. It doesn't work well, is Debian-specific, is misleading, has no documentation. I also have had zero reports of anybody using it whatsover, in Debian or any downstream distribution.

> If you are committed to keeping 6a9e4d0, then Devuan will need to supplement or fork the packaging for redis, which something we'd rather not do if we can help i

This is not a Devuan or init system specific issue thing at all, so I have no idea why 6a9e4d0 would touch on anyones fears any more than any other package in Debian changing behaviour. Forking the packaging would just be creating unnecessary work for literally zero benefit.

I'm afraid I don't follow (or enjoy) your dog kicking, dog leash or remodelling metaphors.

**Comment by blinkdog** [comment]
>>I'm just asking since the functionality is already there, and works well in both systemd and sysvinit systems, will you leave it in place to allow these users a smooth upgrade?

>The smoothest thing to do at this point is remove it early on in the buster release cycle. It doesn't work well, is Debian-specific, is misleading, has no documentation. I also have had zero reports of anybody using it whatsover, in Debian or any downstream distribution.

>>If you are committed to keeping 6a9e4d0, then Devuan will need to supplement or fork the packaging for redis, which something we'd rather not do if we can help it.

>This is not a Devuan or init system specific issue thing at all, so I have no idea why 6a9e4d0 would touch on anyones fears any more than any other package in Debian changing behaviour. Forking the packaging would just be creating unnecessary work for literally zero benefit.

Okay. Sounds to me like you're committed to 6a9e4d0.
I thought I'd ask, just in case. Again, no hard feelings.

>I'm afraid I don't follow (or enjoy) your dog kicking/leash metaphors.

I apologize. I thought the metaphors would be enjoyable and build rapport. Please accept my direct translations below, and my assurances that I won't stray into metaphor again.

"They just knew it was going to kick their puppy sooner or later, and was that a dog yelping just now?"
--> People get worked up easily about things they are afraid of. The DNG folks are afraid of things like 6a9e4d0.

"The truth is closer to puppy's leash was moved to a different hook."
--> 6a9e4d0 is not as bad as the people on the DNG list thought.

"can we move the leash back, or is that wall part of the remodeling plans?"
--> Are you committed to 6a9e4d0 or is it something you are comfortable rolling back?

"I will tell them that you are reasonable and not a puppy kicker, even if we have to install a new leash hook."
--> Even if you are committed to 6a9e4d0, I don't think it makes you a bad person or maintainer, it just means we have different goals. I will tell the people on DNG that you are a good person, even if we have to make changes downstream.

**Comment by kilobyte** [comment]
@blinkdog: this is why it's best to wait until an **actual user** reports this.  Cutting down a feature no one uses means less maintenance work, both for the Debian maintainer and for any downstreams.

As for the DNG thread, beside (too many) opinion pieces, it did include also some real info.  It surprises me you did file this report without reading the thread in its entirety.

(I haven't ever used *redis* thus I have no monkey in this fight, but it'd be good to not cause noise without doing the research.)

**Comment by blinkdog** [comment]
>@blinkdog: this is why it's best to wait until an actual user reports this. Cutting down a feature no one uses means less maintenance work, both for the Debian maintainer and for any downstreams.

>As for the DNG thread, beside (too many) opinion pieces, it did include also some real info. It surprises me you did file this report without reading the thread in its entirety.

>(I haven't ever used _redis_ thus I have no monkey in this fight, but it'd be good to not cause noise without doing the research.)

Thank you for your kind advice, it is appreciated.

**Comment by lamby** [comment]
@blinkdog I think I just don't understand what goal you are aiming for. AIUI Devuan is mostly about a non-systemd version of Debian but — as I've mentioned countless times — this change is completely initsystem agnostic - I actually believe in that.

Anyway, can only see myself rolling this back at this point if I got a large number concrete reports from users saying they require this feature and adjusting the sysvinit script (or systemd unit) was literally impossible for some reason or reasons I have overlooked.

I note that my response to the DNG thread has been moderated away.

**Comment by blinkdog** [comment]
>@blinkdog I think I just don't understand what goal you are aiming for. AIUI Devuan is mostly about a non-systemd version of Debian but — as I've mentioned countless times — this change is completely initsystem agnostic - I actually believe in that.

>Anyway, can only see myself rolling this back at this point if I got a large number concrete reports from users saying they require this feature and adjusting the sysvinit script (or systemd unit) was literally impossible for some reason or reasons I have overlooked.

The change itself is init system agnostic; the service state change hooks are removed across the board (sysvinit, systemd, etc.).

However, the impact on different init systems is also different. For example, let's take user Alice who has a script `phosphoromancy.sh` which loads photonics data into the redis cache when the service starts.

When Alice upgrades from Debian Stretch to Debian Buster, her script will break. She will turn to Debian forums and ask: "Hey, how do I make my script work again?" The answer will be "Go to the systemd unit for redis, and add this line."

    ExecStartPost=/path/to/phosphoromancy.sh 

When Alice upgrades from Devuan Beowulf to Devuan $(Beowulf+1), her script will break. She will turn to Devuan forums and ask: "Hey, how do I make my script work again?" The answer will be, "First, find /etc/init.d/redis-server, and add a run-parts hook". In the sysvinit case, Alice is in for a little more work.

And, believe me, I understand this is our downstream problem, not your problem. I was only asking in case you're comfortable leaving the functionality in place. I have zero concrete reports of this functionality being used, so you're probably not interested in keeping it for the sake of a phantom downstream user. No worries, and no hard feelings.

>I note that my response to the DNG thread has been moderated away.

I was unaware that you had responded. I asked a moderator to please release your response to DNG.

**Comment by lamby** [comment]
> When Alice upgrades from Debian Stretch to Debian Buster, her script will break

Well, this kinda assumes Alice actually exists, which I actually highly doubt. ;)

>  "First, find /etc/init.d/redis-server, and add a run-parts hook". In the sysvinit case, Alice is in for a little more work.

Not at all. She does not need to add a run-parts hook, she can simply call the script directly or inline it in ``/etc/init.d/redis-server`` like she would have to do for literally any other Debian package :)  Special-casing Redis with these hooks is thus highly misleading and not very useful for users. :)

**Comment by blinkdog** [comment]
>>When Alice upgrades from Debian Stretch to Debian Buster, her script will break
>Well, this kinda assumes Alice actually exists, which I actually highly doubt. ;)

This point is well made. I'm going to close the pull request. If we get any users downstream who need this functionality, I'll come back and re-open it, and we can discuss on concrete cases rather than theoretical users.

**Pull request closed without merging**
